### ISSUE TITLE
DatePicker component does not support all props in android as mentioned in the docs.

### ISSUE THREAD

**Issue by pakkibokati2012** [saddlebackdev/hc-mobile-app-ui#81]
We require minimumDate and maximumDate props to be applied all over the place. We have actually missed to spread the rest operator at line 130 in date-picker.tsx

**Comment by ajaybushel** [comment]
@pakkibokati2012 From our discussion, looks like you have already identified the issue that is causing this problem. Can you please create a PR with the fix and reference this issue int he PR?

Thanks

**Comment by raoufr** [comment]
@pakkibokati2012 do we have a PR already created for this issue?

**Comment by raoufr** [comment]
@pakkibokati2012 if the related PR is already merge, we should probably close this issue. Let me know please. thanks
